/**
 * @file PTDN001A.h
 * @brief Dihedral group D₁₂ (§1.2)
 *
 * Component: PTDN001A
 * Domain: PT (Pitch) | Category: DN (Dihedral)
 *
 * The dihedral group D₁₂ of order 24, generated by transposition T
 * and inversion I, acting on pitch classes in Z/12Z.
 *
 * Invariants:
 * - d12_compose(g, d12_identity()) == g
 * - d12_compose(g, d12_inverse(g)) == d12_identity()
 * - d12_apply(d12_compose(a, b), x) == d12_apply(a, d12_apply(b, x))
 * - |d12_apply_set(g, S)| == |S|
 */

#pragma once

#include "../Tensor/TNTP001A.h"
#include "PTPC001A.h"
#include "PTPS001A.h"

#include <array>
#include <string>
#include <vector>

namespace Sunny::Core {

/**
 * @brief Element of the dihedral group D₁₂
 *
 * Represents either a transposition Tₖ (is_inversion = false)
 * or an inversion Iₖ (is_inversion = true).
 */
struct D12Element {
    bool is_inversion = false;
    uint8_t k = 0;  ///< subscript ∈ [0, 11]

    bool operator==(const D12Element&) const = default;
};

/// Construct transposition element Tₖ
[[nodiscard]] constexpr D12Element d12_T(int k) noexcept {
    return {false, static_cast<uint8_t>(((k % 12) + 12) % 12)};
}

/// Construct inversion element Iₖ
[[nodiscard]] constexpr D12Element d12_I(int k) noexcept {
    return {true, static_cast<uint8_t>(((k % 12) + 12) % 12)};
}

/// Group identity T₀
[[nodiscard]] constexpr D12Element d12_identity() noexcept {
    return {false, 0};
}

/**
 * @brief Compose two D₁₂ elements (§1.2)
 *
 * Composition law:
 * - Tₐ ∘ Tᵦ = T₍ₐ₊ᵦ₎
 * - Tₐ ∘ Iᵦ = I₍ₐ₊ᵦ₎
 * - Iₐ ∘ Tᵦ = I₍ₐ₋ᵦ₎
 * - Iₐ ∘ Iᵦ = T₍ₐ₋ᵦ₎
 */
[[nodiscard]] constexpr D12Element d12_compose(D12Element a, D12Element b) noexcept {
    int ak = a.k;
    int bk = b.k;
    if (!a.is_inversion && !b.is_inversion) {
        return d12_T(ak + bk);
    }
    if (!a.is_inversion && b.is_inversion) {
        return d12_I(ak + bk);
    }
    if (a.is_inversion && !b.is_inversion) {
        return d12_I(ak - bk);
    }
    // Both inversions
    return d12_T(ak - bk);
}

/// Group inverse: T⁻¹ₖ = T₍₋ₖ₎, I⁻¹ₖ = Iₖ
[[nodiscard]] constexpr D12Element d12_inverse(D12Element g) noexcept {
    if (g.is_inversion) {
        return g;  // Involutions: I² = e
    }
    return d12_T(-static_cast<int>(g.k));
}

/// Apply element to a pitch class: Tₖ(x) = x+k, Iₖ(x) = k-x
[[nodiscard]] constexpr PitchClass d12_apply(D12Element g, PitchClass x) noexcept {
    if (g.is_inversion) {
        return static_cast<PitchClass>((g.k - x + 12) % 12);
    }
    return static_cast<PitchClass>((x + g.k) % 12);
}

/// Apply element to a pitch class set
[[nodiscard]] PitchClassSet d12_apply_set(D12Element g, const PitchClassSet& s);

/// Order of element in the group
[[nodiscard]] constexpr int d12_order(D12Element g) noexcept {
    if (g.is_inversion) return 2;
    if (g.k == 0) return 1;
    // Order of Tₖ in Z₁₂ = 12 / gcd(k, 12)
    int a = g.k, b = 12;
    while (b) { int t = b; b = a % b; a = t; }
    return 12 / a;
}

/// All 24 elements of D₁₂ (T₀..T₁₁, I₀..I₁₁)
[[nodiscard]] constexpr std::array<D12Element, 24> d12_elements() noexcept {
    std::array<D12Element, 24> elems{};
    for (int i = 0; i < 12; ++i) {
        elems[i] = d12_T(i);
        elems[12 + i] = d12_I(i);
    }
    return elems;
}

/**
 * @brief Conjugacy classes of D₁₂
 *
 * D₁₂ has 9 conjugacy classes:
 * {T₀}, {T₆}, {T₁,T₁₁}, {T₂,T₁₀}, {T₃,T₉}, {T₄,T₈}, {T₅,T₇},
 * {I₀,I₂,I₄,I₆,I₈,I₁₀}, {I₁,I₃,I₅,I₇,I₉,I₁₁}
 */
[[nodiscard]] std::vector<std::vector<D12Element>> d12_conjugacy_classes();

/**
 * @brief Named subgroup of D₁₂
 */
struct D12Subgroup {
    std::string name;
    std::vector<D12Element> elements;
};

/**
 * @brief Generate subgroup from a set of generators
 *
 * Repeatedly composes generators until closure.
 */
[[nodiscard]] std::vector<D12Element> d12_generate(
    std::span<const D12Element> generators
);

/**
 * @brief Enumerate musically relevant subgroups
 *
 * Returns cyclic subgroups (Z₁..Z₁₂) and dihedral subgroups
 * (D₁..D₁₂) with canonical generators.
 */
[[nodiscard]] std::vector<D12Subgroup> d12_named_subgroups();

}  // namespace Sunny::Core
